import React from 'react';
import { ArrowUpRight, ArrowRight, Plus, Layers3 } from 'lucide-react';

export default function Home({ modes, game, setScreen }) {
  return <div className="home-screen screen-enter">
        <div className="hero-copy"><div className="eyebrow"><span className="tiny-star">✳</span> GOOD COMPANY. GREAT GAMES.</div><h1>Less counting.<br/>More <span className="highlight-word">playing.<svg viewBox="0 0 310 16" preserveAspectRatio="none"><path d="M3 10 Q140 -2 305 7 M20 14 Q160 6 291 12"/></svg></span></h1><p className="hero-description">Keep the score. Keep the moment.<br/>Your little sidekick for every game night.</p><button className="primary new-game" onClick={() => setScreen('setup')}><Plus size={23}/><span>New game</span><ArrowUpRight size={23}/></button>{game && <button className="resume-button" onClick={() => setScreen('game')}>Pick up your {game.finished ? 'last' : 'current'} game <ArrowRight size={16}/></button>}<div className="hero-footnote"><span className="mini-avatars"><i>A</i><i>J</i><i>M</i></span><span>For your people. And a little friendly rivalry.</span></div></div>
        <div className="hero-art" aria-label="Illustration of a game scoreboard with Alex at 24 points and Jamie at 18 points"><div className="art-orbit orbit-one"/><div className="art-orbit orbit-two"/><span className="art-spark spark-one">✳</span><span className="art-spark spark-two">✧</span><div className="floating-label"><span className="status-dot"/> GAME NIGHT, SORTED.</div><div className="playing-card card-back"><span>♧</span></div><div className="playing-card card-front"><span>A<small>♠</small></span><b>♠</b><span className="card-corner">A<small>♠</small></span></div><div className="demo-board"><div className="demo-heading"><span>THE FRIENDLY RIVALRY</span><span className="live-dot"/></div><div className="demo-round">Round 3 <span>/ 5</span><Layers3 size={17}/></div><div className="demo-player lavender"><span className="demo-avatar">A</span><span>Alex<small>On a roll ✨</small></span><strong>24</strong></div><div className="demo-player peach"><span className="demo-avatar">J</span><span>Jamie<small>Still in the game</small></span><strong>18</strong></div><div className="demo-bottom"><span><span className="small-check">✓</span> Math? Handled.</span><span>You're up. <ArrowRight size={13}/></span></div></div><div className="dice"><i/><i/><i/><i/><i/></div><div className="art-caption">a little less math, a lot more moments.<svg viewBox="0 0 50 38"><path d="M2 4 Q45 0 40 30 M29 22 L40 31 L47 20"/></svg></div></div>
        <section className="ways-section"><div className="section-heading"><span>ONE SCOREKEEPER. EVERY KIND OF GAME.</span><span className="section-line"/></div><div className="ways-grid">{modes.map(({ id, icon: Icon, short, text }) => <div className="way" key={id}><div className="way-icon"><Icon size={22} strokeWidth={1.6}/></div><div><h3>{short}</h3><p>{text}</p></div></div>)}</div></section>
      </div>;
}
